name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.0.2'
        architecture: x64
    - name: Run docke
      run: |
        git --no-pager show $(git log --pretty=format:'%h' -n 2 | tail -n 1):autocd.json 2>/dev/null 1>oldautocd.json || true
        curl -L https://github.com/kloudsoftware/AutoCD/releases/download/alphav1/AutoCD-1.0.jar -o app.jar
        java -Djdk.tls.client.protocols=TLSv1.2 -jar app.jar
      env:
        KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        AUTOCD_DOMAIN_BASE: .kloud.software
        CI_REGISTRY_USER: ${{ secrets.CI_REGISTRY_USER }}
        CI_REGISTRY_PASSWORD: ${{ secrets.PAT }}
        K8S_REGISTRY_USER_TOKEN: ${{ secrets.PAT }}
        K8S_REGISTRY_USER_NAME: ${{ secrets.CI_REGISTRY_USER }}
        CI_REGISTRY: ghcr.io
        ORG_NAME: kloudsoftware
        K8S_SECRET_NEEDED: true
        K8S_STORAGE_CLASS: nfs-client
        AUTOCD_ENV: GITHUB
        BUILD_TYPE: prod

